server:
  port: 8080

spring:
  profiles:
    active: dev
  application:
    name: lc-predictor

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: deleted

logging:
  file:
    name: tmp/server.log
