server:
  port: 8080

spring:
  application:
    name: lc-predictor
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lc_predictor
    username: root
    password: root

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: deleted

logging:
  file:
    name: tmp/server.log
